name: ESLint check

on:
  pull_request:
    types: [opened, synchronize]
    branches: ['main']

jobs:
  eslint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

  steps:
    - name: Checkout code
      uses: actions/checkout@v24
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm run lint
